<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions 
xmlns:tns="urn:xeu:connector-bridge:wsdl:v1" 
xmlns:bridge="urn:xeu:connector-bridge:v1" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
name="bridge" 
targetNamespace="urn:xeu:connector-bridge:wsdl:v1">
	<wsdl:documentation>Version: 1.0 RC 20130606</wsdl:documentation>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="urn:xeu:connector-bridge:v1"
			schemaLocation="connector-bridge-payload.xsd"/>			
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="postRequest">
		<wsdl:part name="parameter" element="bridge:POSTMSG"/>
	</wsdl:message>
	<wsdl:message name="postResponse">
		<wsdl:part name="output" element="bridge:POSTMSGOUT"/>
	</wsdl:message>
	<wsdl:portType name="BridgeConnectorPortType">
		<wsdl:operation name="post">
			<wsdl:input message="tns:postRequest"/>
			<wsdl:output message="tns:postResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BridgeConnectorSOAP11Binding" type="tns:BridgeConnectorPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="post">
			<soap:operation soapAction="urn:xeu:connector-bridge:wsdl:v1:post"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BridgeConnectorService">
		<wsdl:port name="BridgeConnectorSOAP11Port" binding="tns:BridgeConnectorSOAP11Binding">
			<soap:address location="http://localhost/connector"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
